GET http://localhost/api/users-management/users?page=1&size=5&sort=name

###

POST http://localhost/api/users-management/users
Content-Type: application/json

{
  "name" : "НеМарсель",
  "email" : "notmarselmail@gmail.com",
  "password": "sd7a9s8f79912879q7a9a9qwqaqq"
}

###

